window=global;
delete global;
window['__VUE__']=true;
Object.defineProperty(window,Symbol.toStringTag, {
        value: 'Window'
});
location={
    "ancestorOrigins": {},
    "href": "https://tool.liumingye.cn/music/#/search/M/song/some",
    "origin": "https://tool.liumingye.cn",
    "protocol": "https:",
    "host": "tool.liumingye.cn",
    "hostname": "tool.liumingye.cn",
    "port": "",
    "pathname": "/music/",
    "search": "",
    "hash": "#/search/M/song/some"
}
var Location=function (){};
location.__proto__=Location.prototype;
Object.defineProperty(location,Symbol.toStringTag, {
        value: 'Location'
});
r=function Co(e, t) {
    const n = qo();
    return (Co = function(e, t) {
        return n[e -= 237]
    }
    )(e, t)
}
const CryptoJS=require('crypto-js')
 Ps = r(1784);
var Is = r(280)
  , Es = r(2206)
  , Ls = "string"
  , js = r(1301)
Ns = function(e) {
    return typeof e
}
function Os(e, t) {
    const n = r
      , s = {
        LNpaQ: function(e, t) {
            return e !== t
        },
        mahyG: function(e, t) {
            return e !== t
        },
        cHrmj: function(e, t) {
            return e === t
        }
    };
    var o = t[n(679)]("")
      , i = 114514;
    return i = s[n(698)](Ns(window), Es) ? 4 : Ns(window[n(952)]) !== Es || s[n(2001)](Ns(window[n(952)].host), Ls) ? 3 : Ns(window[n(2102)]) !== Es || s.LNpaQ(Ns(window[n(2102)][n(1841)]), Ls) ? 2 : s[n(937)](Ns(window[n(1732)]), js) && !0 === window[n(1732)] ? 1 : 0,
    o[n(1254)]((function(t, n) {
        return t.charCodeAt(0) ^ function(e, t) {
            const n = r;
            return e[n(341)](Math[n(680)](t % e.length))
        }(e, n + i - 1)
    }
    ))
}
As = function(e) {
    const t = r;
    return Object[t(1076)][t(1750)][t(1355)](e).slice(8, -1)[t(2213)]()
}
Ds = function() {
    const e = r
      , t = {
        uOQDU: function(e, t) {
            return e(t)
        }
    };
    e(1337),
    Date[e(1992)]();
    return Ns(window) !== Es ? e(1162) : t[e(1833)](Ns, window[e(952)]) !== Es || Ns(window[e(952)][e(1725)]) !== Ls ? e(2119) : t[e(1833)](Ns, window[e(2102)]) !== Es || Ns(window[e(2102)][e(1841)]) !== Ls ? e(2301) : Ns(window.__VUE__) === js && !0 === window.__VUE__ ? "xeLO3Wq54bYyE5q59B1WU0ju26bg5GzZTr7wN40aOYOEZEy9IWm9XU51an5nv2jp" : "fuosrbnnmcikvotxwlajwfcyhhzmkjbyzsiageteqxupdgqprvdl"
};
function qo() {
    return  [
        "-0.1s",
        "100",
        "scrollLeft",
        "Sjffq",
        "adjustPosition",
        "contents",
        "granim:end",
        "https://i.biliimg.com/bfs/im/5e1bb206013edfc359509b33e32ff2ca046d2f88.png@{size}w_{size}h_1c.webp",
        "liebiaoxunhuan",
        "string",
        "clearloadErrorTime",
        "2.5x",
        "playQueue.nowPlaying",
        "flex flex-col flex-1 w-full md:max-w-[30vmax] md:justify-center md:mr-8 <md:justify-end my-2vh transition-all duration-500",
        "overflow-hidden",
        "SongList",
        "杨千嬅",
        "NaCMj",
        "py-50vh",
        "min-h-80 p-4",
        "data-v-da83167e",
        "colorsPos",
        "SyGHa",
        "playlist",
        "繁體中文",
        "https://p1.music.126.net/XkiM2BZ75QvBt44Jk3y6-g==/109951163520866955.jpg?param={size}y{size}",
        "ml-$sider-width",
        "slots",
        "settings.account",
        "mr-2",
        "diagonal",
        "flex-x-center <sm:justify-between",
        "directive",
        "修改失败",
        "canvas-interactive",
        "Asgyn",
        "tooltipTextColor",
        "uploadImg",
        "model",
        "flex justify-between px-5 <md:px-2",
        "wrapperRef",
        "basis-100px",
        "assign",
        "mLIXG/KZejUbq85HWdvlVtpAFrQsR0ciYEDPJwn321zu4=ToxygSM67OkafC9hNB+",
        "mount",
        "range",
        "touchmove",
        "file",
        "menu.home",
        "flex-y-center font-medium text-2xl font-smiley",
        "[artist]",
        "previoustrack",
        "莫文蔚",
        "background-color",
        "https://p1.music.126.net/NjkDrM9njCsZ1UTynMGbDg==/109951167065627347.jpg?param={size}y{size}",
        "z3Ol",
        "GyWxD",
        "https://p1.music.126.net/YDKUscOIKTm7Ko7KyKWggw==/3346913395417148.jpg?param={size}y{size}",
        "https://p1.music.126.net/qLLALOy08DZJO9raDsWeEg==/109951163664620182.jpg?param={size}y{size}",
        "undefined",
        "customRender",
        "fade",
        "soft-light",
        "UFOUZ",
        "catch",
        "NoAX",
        "POST",
        "mx-context-menu-updown mx-context-no-clickable down",
        "rgba(193, 200, 209, 0.6)",
        "vXLoz",
        "max-w-100vw",
        "hqAYz",
        "https://p1.music.126.net/jZIXAvWz0o-kE-U8Ootskg==/109951166501994786.jpg?param={size}y{size}",
        "lazy",
        " / ",
        "customClass",
        "offsetParent",
        "Oalyc",
        "zMl7",
        "nexttrack",
        "<lg:flex-1 flex flex-col",
        "w-16 h-16 rounded-lg mr-4 flex-shrink-0",
        "focus",
        "1500px",
        "dGCGZ",
        "submenu",
        "text-btn",
        "svg",
        "state",
        "uZkCc",
        "reloadPrompt.needRefresh",
        "ZmegO",
        "clamp",
        "resolve",
        "取回密码的方法已通过 Email 发送到您的信箱中，请在 3 天之内修改您的密码",
        "⌘/Ctrl",
        "udmuq",
        "https://p1.music.126.net/BO0kDJYEoGuUwjMT5oyHRw==/109951167710097414.jpg?param={size}y{size}",
        " 找回密码 ",
        "globalCloseMenu",
        "YUzSt",
        "data-v-b6395527",
        "GvZgZ",
        "https://pl-fe.cn/cloud-music-api",
        "charCodeAt",
        "gmhGL",
        "absolute top-1.5",
        "ontouchmove",
        "bodyRef",
        "change:select",
        "wfFlV",
        "isReady",
        "NjcaW",
        "公开成功",
        "/passwordfind/:uid?/:verify_code?",
        "收藏歌单",
        "relative w-40px h-40px rounded-1 z-1",
        "OzavF",
        "round",
        "minWidth",
        "JUgxT",
        "DOWN",
        "https://p1.music.126.net/8_cpEv3Qt-0puHoq89elbA==/109951165027027385.jpg?param={size}y{size}",
        "CancelToken",
        "prefixCls",
        "defaultStateName",
        "data-v-4f7af1f1",
        "font-medium",
        "VOxoY",
        "removeEventListener",
        "BUXtQ",
        "addedNodes",
        "create_time",
        "./lang/ja-JP.9237fee5.js",
        "收藏成功",
        "setup",
        "#canvas-interactive",
        "BAKYe",
        "width",
        "text-btn !text-inherit",
        "nELdO",
        "Artist:",
        "set",
        "./workbox-window.prod.es5.bb1c7045.js",
        "50px",
        "用户名最多为20个字符",
        "RnMMo",
        "FNdBR",
        "text",
        "modulepreload",
        "min-w-12",
        "https://p1.music.126.net/cBW-awheYxln_RXFrohh_Q==/109951165080289545.jpg?param={size}y{size}",
        "cross-site",
        "mb-2",
        "抱歉，页面不见了～",
        "scrollValue",
        "ml-2 flex-shrink-0 text-btn",
        "https://p1.music.126.net/QiBRSyqAVr8HaTcF3db9DQ==/109951165941637692.jpg?param={size}y{size}",
        "歌单名",
        "d13899303",
        "TopMenu",
        "content-style",
        "KIpur",
        "获取session失败。",
        "eventPolyfill",
        "!mb-1",
        "-icon",
        "!pb-4",
        "gradient.color",
        "SoJOF",
        "#app",
        "https://p1.music.126.net/UxM5Hr-t16-dwpgMfri-Mw==/6048413465039896.jpg?param={size}y{size}",
        "theme",
        "stretch",
        "https://p1.music.126.net/uTwOm8AEFFX_BYHvfvFcmQ==/109951164232057952.jpg?param={size}y{size}",
        "position",
        "isCanvasInWindowView",
        "keepData",
        "back",
        "flex-y-center cursor-pointer font-medium text-2xl mb-2 font-smiley",
        "yvOOt",
        "wRtHw",
        "centerY: ",
        "邮箱不能为空",
        "download.title",
        "1400px",
        "kMG7",
        "overflow-hidden rounded",
        "-content",
        "fixed top-0 left-0 w-$sider-width h-full bg-[rgb(var(--gray-2))] pb-$fotter-height",
        "https://p1.music.126.net/A29AvNO-UD5iRl_LtuBlrw==/109951165139737007.jpg?param={size}y{size}",
        "-mt-2 text-$color-neutral-6",
        "rawLrc",
        "SYeal",
        "https://p1.music.126.net/Ga4N1OpNuRDwy0g4ByxTVw==/109951163498751996.jpg?param={size}y{size}",
        "settings.themeSubtitle",
        "bubbles",
        "setTimeout",
        "system",
        "XVlbC",
        "bscQH",
        "IUFYk",
        "preventDefault",
        "kpA4",
        "download.192",
        "suijibofang1",
        "Artist",
        "data-v-15aa49e3",
        "self",
        "emit",
        "jkncA",
        "SKGyN",
        "download.method1",
        "张韶涵",
        "KZBjy",
        "animate",
        "该歌曲为纯音乐请欣赏",
        "email",
        "N8KD",
        "WrGgO",
        "kpq7",
        "setDirection",
        "targetElement",
        "data-v-c2805aad",
        "/search/:engine",
        "namedRules",
        "设置密码成功",
        "onClose",
        "cxyMU",
        "mx-context-menu ",
        "w-44px h-44px",
        "show",
        "removeListeners",
        "#222",
        "src",
        "data-v-f722aecb",
        "mr-0.1 superellipse",
        "component",
        "https://p1.music.126.net/2aCqy2k9cIMzJDd0TU9CMg==/109951164513946258.jpg?param={size}y{size}",
        "data-v-0dcbc61d",
        "setVolume",
        "settings.preset2",
        "topMenu.recent",
        "hue",
        "fallbackLocale",
        "SFMWR",
        "contextmenu.copyname",
        "PlayerState",
        "lyricRef",
        "DwYQi",
        "cache",
        "添加收藏成功",
        "kgOV",
        "transition bg-auto flex-1 h-9 leading-9 px-4 cursor-pointer hover:bg-$color-fill-3 text-$color-neutral-8 rounded-6xl",
        "categories",
        "p-3",
        "sessionStorage",
        "setAttribute",
        "volumeValue",
        "exit",
        "clientHeight",
        "PYRUS",
        "error",
        "infinite-load",
        "flex-y-center justify-end",
        "zfkZT",
        "VEHfz",
        "var(--black)",
        "GnIpn",
        "playAll",
        "LJnjf",
        "onStart",
        "UlTkO",
        "activetransitionSpeed",
        "findCurrentIndex",
        "requestAnimationFrame",
        "buffer",
        "scrollbars=1,resizable=0,width=690,height=620",
        "min-h-0 text-center",
        "seekOffset",
        "1|5|4|0|3|2",
        "knxP",
        "elastic.out(1,0.3)",
        "DarkVibrant",
        "validateInput",
        "XqULR",
        "then",
        "checkCloseOtherSubMenuTimeOut",
        "k2n7",
        "zEla",
        "0|2|3|4|1",
        "line-container",
        "dZNsA",
        "歌单描述",
        "kAO4",
        "addSong",
        "登录失败",
        "menuContext",
        "沈以诚",
        "element",
        "rShDg",
        "oyFOC",
        "768px",
        "flex mb-2 justify-between",
        "创建歌单失败！",
        "MyFreeMP3",
        "Lrebc",
        "Beyond",
        "[artist] - [name]",
        "percent",
        "flex-none",
        "pt-[100%]",
        "endsWith",
        "dkBWs",
        "total",
        "seekbar flex-1",
        "https://p1.music.126.net/xQHd2jGf6z0thNcNamwBhQ==/109951166566542419.jpg?param={size}y{size}",
        "download.lyric",
        "kY5V",
        "resize",
        "isEdit",
        "mb-4",
        "cacheTime",
        "scrollDebounceTimeout",
        "fromTo",
        "tagName",
        "convertColorToRgba",
        "Auth",
        "close",
        "showRightArrow",
        "ItLNW",
        "992px",
        "offsetTop",
        "/api/auth/login",
        "ml-2px",
        "isPlaying",
        "ghhWF",
        "no-underline",
        "flex-1 flex items-center space-x-4 border-b py-4",
        "Explore",
        "select",
        "请等待验证程序初始化完成",
        "EPwiq",
        "path",
        "ctrl_arrowleft",
        "qB2g",
        "activeColorsDiff",
        "JlDZ",
        "rate",
        "ref",
        "large",
        "#000",
        "more",
        "mRqGg",
        "OqShd",
        "编辑歌单信息",
        "createRadialGradient",
        "NEZCf",
        "font-medium text-xl",
        "user",
        "./sw.js",
        "stretch-if-smaller",
        "right",
        "qNqGR",
        "align",
        "canplay",
        "table.artist",
        "channels",
        "李克勤",
        "福禄寿FloruitShow",
        "NJM6",
        "default",
        "公开歌单",
        "User",
        "ttshN",
        "https://p1.music.126.net/CsGY6JmX21cxa-5DZKIqpQ==/109951164546544248.jpg?param={size}y{size}",
        "overflow",
        "姜云升",
        "flex flex-col h-38px justify-between overflow-hidden",
        "https://p1.music.126.net/02owJjzGzmqqL7QxU51s3w==/109951164503325260.jpg?param={size}y{size}",
        "tooltipColor",
        "ejzih",
        "hex",
        "text-lg font-medium leading-64px",
        "flex-1 text-$color-text-2",
        "info",
        "https://p1.music.126.net/hW6-ryM6s1UO-3fSMyLt-w==/109951165604261641.jpg?param={size}y{size}",
        "ZkPPG",
        "qAdrE",
        "gJSyT",
        "imagePosition",
        "UVagD",
        "searchEngine",
        "currentSong",
        "rgb(var(--primary-6))",
        "bPpOF",
        "h-15 leading-15 w-12 mx-0 px-1",
        "exec",
        "vUFlN",
        "你的昵称",
        "https://i.biliimg.com/bfs/im/acf0e19c3faa42d8667495c14f2929df4f467255.png@{size}w_{size}h_1c.webp",
        "lyricSize",
        "300px",
        "isUpdate",
        "scrollHeight",
        "top",
        "TBvdh",
        "mask",
        "UFRHU",
        "smooth",
        "classic",
        "loading",
        "vOXMI",
        "Song",
        "data-v-d2b5db8f",
        "Seekbar",
        "tag-click",
        "https://paopaoshequ.com",
        "table.album",
        "add",
        "activated",
        "backend",
        "lastLock",
        "ResizeObserver",
        "320",
        "DSVVu",
        "shuffleSongList",
        "/api/auth/password/set",
        "activeColors",
        "display",
        "innerHTML",
        "onerror",
        "step",
        "pos",
        "px-4 pt-3",
        "Space",
        "seekto",
        "https://c.y.qq.com/splcloud/fcgi-bin/smartbox_new.fcg",
        "#d5d5d5",
        "showSaveFilePicker",
        "artists",
        "image",
        "split",
        "floor",
        "enter",
        "mouseup",
        "NAxB",
        "download.96",
        "lighten",
        "576px",
        "font-medium text-2xl mb-2 font-smiley",
        "default-state",
        "link",
        "bind",
        "金玟岐",
        "UMPFo",
        "keys",
        "retry",
        "contains",
        "all",
        "flex my-2px",
        "LNpaQ",
        "这个家伙很懒,什么都没有留下",
        "flex-center min-w-15 font-bold",
        "服务器繁忙，请稍后重试。",
        "/api/miauth/callback?session=",
        "sYdNE",
        "fKSXA",
        "当前浏览器版本不支持",
        "mx-context-menu-items",
        "onBlur",
        "uPiGq",
        "BEHTi",
        "flex justify-between mb-4",
        "reject",
        "$slots",
        "hotkey",
        "rounded-full",
        "timers",
        "opacity-0 pointer-events-none",
        "waiting",
        "onSuccess",
        "longpress",
        "https://i.biliimg.com/bfs/im/83df6dcc856c791c0f0159dbc7a1c7c0d28d5c06.jpg@{size}w_{size}h_1c.webp",
        "private",
        "包含歌曲列表",
        "-title",
        "0.375rem",
        "*/*",
        "d27868624",
        "8|5|1|0|6|7|2|3|4",
        "w-max will-change-transform",
        "clientY",
        "#FFF",
        "ncOLv",
        "hasOwnProperty",
        "https://p1.music.126.net/SJnVAjDS4GCSxv7-hPu5uw==/109951164831722513.jpg?param={size}y{size}",
        "data-postimg",
        "reserveScrollBarGap",
        "script",
        "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
        "基本信息",
        "한국어",
        "EXCJV",
        "BgWrapper",
        "周兴哲",
        "找回密码",
        "kaMP",
        "https://p1.music.126.net/Dm_L6BDLfy5j7vkTiJomYA==/109951166674895412.jpg?param={size}y{size}",
        " 如有侵权，请联系本人予以删除！邮箱liumingye2015@gmail.com",
        "gradientLength",
        "settings.themeColorMode",
        "cUzZg",
        "addsub",
        "showPlayQueue",
        "top-0",
        "circle",
        "isPausedWhenNotInView",
        "link[rel=\"modulepreload\"]",
        "render",
        "data-v-e151f7b0",
        "playlistCoverUpdate",
        "zh-CN",
        "colorsDiff",
        "__scopeId",
        "/my",
        "order-2 my-4 flex-1",
        "setActionHandler",
        "scroll",
        "fillStyle",
        "陈一发",
        "排序失败",
        "h-[calc(100vh-1px)]",
        "OccfH",
        "count",
        "autoplay",
        "https://p1.music.126.net/EL2R9tzkaLvpAkDpNTlxIQ==/109951165443367321.jpg?param={size}y{size}",
        "imageNode",
        "style",
        "https://gist.githubusercontent.com/",
        "王心凌",
        "true",
        "bg-$black text-white",
        "data",
        "timeupdate",
        "pos: ",
        "vYna",
        "data-v-5945495a",
        "https://p1.music.126.net/ZSU2mgF43Pv6vsYneprVWw==/109951165818611746.jpg?param={size}y{size}",
        "startsWith",
        "text-sm",
        "gradients",
        "Granim: Input error on \"",
        "icon-sound",
        "scrollTo",
        "promise",
        "text-center w-50 mt-5",
        "RtqMN",
        "index",
        "contextmenu.viewAlbum",
        "isCleared",
        "./resize-observer.36dc943a.js",
        "fVTVO",
        "allowTouchMove",
        "https://p1.music.126.net/FWsjo25wumC67z53LXXRUQ==/109951165694813396.jpg?param={size}y{size}",
        "/auth/callback",
        "歌手介绍",
        "Authorization",
        "overlay",
        "iconFontClass",
        "50% 0",
        "isLogin",
        "parentNode",
        "Buvkv",
        "ijdde",
        "settings.openSearch",
        "VzKJs",
        ".flac",
        "WPP1",
        "d29235210",
        "var(--blue)",
        "GEGrK",
        "SongItem",
        "showLyric",
        "ontouchstart",
        "updateProgress",
        "flex-shrink-0 bg-auto",
        "杨和苏KeyNG",
        "scrollBehavior",
        "app",
        "link[href=\"",
        "includes",
        "d29393033",
        "https://p1.music.126.net/nmNsl9BXuwoAgB1mQtXCFw==/109951165738539025.jpg?param={size}y{size}",
        "flex-1 font-medium text-xs rounded-full",
        "window",
        "span",
        "small",
        "localStorage",
        "首字母",
        "flex-y-center flex-shrink-0 space-x-2 ml-2 flex-auto sm:max-w-xs",
        "title text-sm truncate font-medium",
        "Iconfont",
        "#f1f1f1",
        "h-10 leading-10 px-2 text-$gray",
        "NotFound",
        "https://p1.music.126.net/N2IEIuGMR7N4vtXfRntDqw==/109951164269428307.jpg?param={size}y{size}",
        "fluid",
        "handle",
        "XOQkt",
        "audioOutput",
        "canvas",
        "/upload?",
        "parse",
        "N1EJ",
        "/api/song/order/update",
        "vEmgR",
        "hsla",
        "Ice Paper",
        [],
        "globalRenderSlot",
        "d50275485",
        "contextmenu",
        "align-middle mr-1",
        "uid",
        "clickableWhenHasChildren",
        "addEventListener",
        "setLyricSize",
        "https://ghproxy.net/",
        "_context",
        "will-change-transform fixed inset-0 z-9",
        "PDwdw",
        "createdOn",
        "JPczh",
        "setMediaMetadata",
        "next",
        "!m-0 !py-4 bg-$color-neutral-2 flex-1 rounded-xl",
        "TLnjK",
        "VNodeRender",
        "toUpperCase",
        "truncate md:text-lg md:px-2",
        "MyTTL",
        "historyList",
        "request",
        "https://i.biliimg.com/bfs/im/30063cfbb804dd8d3ca3362d4410b92a831c0a46.png@{size}w_{size}h_1c.webp",
        "contextmenu.download",
        "search",
        "activeElement",
        "elToSetClassOn",
        "use",
        "ContextMenu",
        "auth.pass",
        "mb-2 pl-10px text-lg",
        "PlayListEdit",
        "mx-context-menu-scroll",
        "ml-1",
        "GUHvv",
        "colorsTo",
        "changeImage",
        "text-xs truncate opacity-65",
        "Tizzy T",
        "Header",
        "offsetLeft",
        "KqmAg",
        "touchcancel",
        "contextmenu.deleteFromList",
        "ipc",
        "has",
        "scrollIntoView",
        "hideClose",
        "GMyEl",
        "cover",
        "XGxEN",
        "wkynH",
        "modal-body flex-shrink-0 pb-$vueuse-safe-area-bottom overflow-x-hidden overflow-y-auto",
        "ja-JP",
        "mt-1 text-lg truncate min-h-28px",
        "https://p1.music.126.net/8HNv_H6Qf0JdRt79nvlHfA==/109951166669433027.jpg?param={size}y{size}",
        "pQ2P",
        "qQegS",
        "prevSongs",
        "UdVOX",
        "ZceUM",
        "default-active-key",
        "余佳运",
        "N1BG",
        "./index.655fa6e9.js",
        "crossorigin",
        "name",
        "loop",
        "type",
        "lighter",
        "update:show",
        "Rw73",
        "XiGrT",
        "MZRUA",
        "kwOk",
        "vars",
        "onBeforeClose",
        "w-full",
        "cHrmj",
        "trim",
        "https://p1.music.126.net/7OoAuH2Iqjr3Owmqf4pNFQ==/109951165912271970.jpg?param={size}y{size}",
        "LyricRightContent",
        "https://npm.elemecdn.com/eruda",
        "crossOrigin",
        "更新失败，请上传jpg,png格式的图片",
        "The element you used is neither a String, nor a HTMLCanvasElement",
        "k8l8",
        "flex-grow",
        "changeBlendingMode",
        "selected-keys",
        "w-full mt-2",
        "!<lg:hidden superellipse",
        "xlink:href",
        "location",
        "100px",
        "externalwaiting",
        "handleClose",
        "歌单创建成功！",
        "slice",
        "https://i.biliimg.com/bfs/im/36b8b87699975bda16d572d137df7343f77fae7a.png@{size}w_{size}h_1c.webp",
        "flex-y-center px-10px py-6px",
        "RCFdZ",
        "options",
        "<p>Test Test Test1</p><p>Test Test Test2</p><p>Test Test Test3</p><p>Test Test Test4</p><p>Test Test Test5</p><p>Test Test Test6</p><p>Test Test Test7</p><p>Test Test Test8</p><p>Test Test Test9</p><p>Test Test Test10</p><p>Test Test Test11</p><p>Test Test Test12</p><p>Test Test Test13</p><p>Test Test Test14</p><p>Test Test Test15</p><p>Test Test Test16</p><p>Test Test Test17</p><p>Test Test Test18</p><p>Test Test Test19</p><p>Test Test Test20</p><p>Test Test Test21</p><p>end</p>",
        "canDrag",
        "noAnimation",
        "adsRef",
        "auth.secureTip",
        "player.next",
        "王嘉尔",
        "currentIndex",
        "text-4xl font-bold mb-12 text-center",
        "cacheData",
        " disabled",
        "absolute w-full h-2px bg-$text",
        "ScrollAnimation",
        "showContextMenu",
        "/api/home/recommend",
        "d1079074",
        "filter",
        "contentRef",
        "font-semibold",
        "TIFRE",
        "添加收藏失败",
        "itemRender",
        "Folder write test",
        "locale",
        "KgLyy",
        "main",
        "isEmpty",
        "Click the icon of the Adblock Plus plug-in in the browser, and click the green 'Enable' button in the pop-up dialog box to disable it. At this time, the ABP icon changes from red to gray, and the operation Success, then press F5 to reload the page.一、如何將本站加入到Adblock插件白名單：點擊瀏覽器AdBlock插件的圖標，在彈出的對話框中點擊“在本網站上暫停AdBlock”，然後按F5重新加載網頁即可。二、如何將本站加入到Adblock Plus插件白名單：點擊瀏覽器Adblock Plus插件的圖標，在彈出的對話框中點擊綠色“啟用”按鈕之後即可禁用，這時候ABP圖標由紅變灰，操作成功，然後按F5重新加載網頁即可。",
        "duration",
        "backdrop-filter backdrop-blur-lg pb-$vueuse-safe-area-bottom fixed bottom-0 left-0 w-full",
        "mb-$fotter-height",
        "getColorPos",
        "https://p1.music.126.net/TBrlu0t5QqKfEcCBOCfwrA==/109951166337304954.jpg?param={size}y{size}",
        "getTime",
        "XRnVQ",
        "512",
        "closeMenu",
        "clearInterval",
        "ArtistsInLine",
        "menu.explore",
        "matchAll",
        "登录密码",
        "歌单名最多20个汉字",
        "none",
        "url",
        "32px",
        "var(--text)",
        "loadError",
        " 设置密码 ",
        "TdWLQ",
        "update:modelValue",
        "fixed pt-18 -top-3 bottom-$fotter-height right-0 bg-$color-bg-2 w-350px max-w-100vw shadow-xl",
        "playQueue.clearList",
        "closed",
        "wUbjR",
        "fcigw",
        "touchstart",
        "integrity",
        "classList",
        "Gmvuj",
        "input",
        "data-v-11e2efe7",
        "font-medium select-text !mb-3 !text-3xl !<sm:text-lg <sm:mb-2",
        "inputRef",
        "getValidate",
        "download.method2",
        "/music",
        "settings.lyricColorMode",
        "changeState",
        "zlrQ",
        "kpP0",
        "调整歌曲顺序",
        "h-full pt-15 pb-$fotter-height z-0",
        "top-bottom",
        "constOptions",
        "Qhdym",
        "w-42px h-42px mr-2 rounded-md",
        "烟(许佳豪)",
        "playerMode",
        "https://p1.music.126.net/vwAaR1GsU-GpNCk9QnXaDg==/109951166653150223.jpg?param={size}y{size}",
        "shape",
        "zYOg",
        "space-between",
        "bNTzR",
        "w-6 flex-center flex-col",
        ".playQueueButton",
        "%cDon't paste unknown code here, your account may be hijacked!",
        "/api/album",
        "volume",
        "RBlJ",
        "currentOffset",
        "pointerEvents",
        "createLinearGradient",
        "player h-25 px-5 <lg:px-2",
        "小一点",
        "760616cTVOrx",
        "/api/playlist/update",
        "kind",
        "毛不易",
        "rounded-2xl shadow-xl max-w-full max-h-full",
        "mobile-nav",
        "relative flex-y-center pt-1 px-3 flex-shrink-0 border-b min-h-13",
        "iMkjD",
        "ZbMoW",
        "ArrowIndicator",
        "auto",
        "confirmpassword",
        "currentColor",
        "fill",
        "ctrl_arrowdown",
        "Eruda",
        "en-US",
        "colorsFrom",
        "menu",
        "prototype",
        "/api/search/playlist",
        "active-key",
        "PmjDO",
        "getDetail",
        "opacity-65",
        "编辑歌单信息失败！",
        "__vccOpts",
        "clickClose",
        "h3R3",
        "querySelectorAll",
        "p-3 md:p-5 max-w-8xl mx-auto",
        "hidden",
        "line-",
        "4DtxAic",
        "indexOf",
        "gnMSa",
        "kVNmK",
        "lyricColor",
        "dPqli",
        "30px",
        "font-medium text-24px w-full bg-transparent text-$text",
        "TagSelect",
        "BtCRJ",
        "https://p1.music.126.net/dvBg6zC0sQNNvl9DdW7p2Q==/109951163267157138.jpg?param={size}y{size}",
        "mElJL",
        "SvuGO",
        "durationchange",
        "mr-1",
        "getElementsByTagName",
        "LSNfb",
        "https://p1.music.126.net/Uz3kQexeEK-HY_pNk3V0UA==/109951166229097647.jpg?param={size}y{size}",
        "speratorRender",
        "globalTheme",
        "N86k",
        "getCurrentColors",
        "Granim: The image source is invalid.",
        "update:showLyric",
        "max-w-100 h-9",
        " 2024.10.16 已支持使用泡泡社区登录。 ",
        "stringify",
        "https://p1.music.126.net/GL0xcgu4OUml509BbW2qAQ==/109951163137467389.jpg?param={size}y{size}",
        "custom",
        "歌单名不能为空",
        "section",
        "onInfiniteLoad",
        "data-v-d141ecf3",
        "checkTargetAndClose",
        "scrollDebounceThreshold",
        "kQhia",
        "UserSecurity",
        "quality",
        "order-1 top-1.5 h-4vh -mt-2vh pt-2vh",
        "params",
        "100%",
        "primary",
        "/auth",
        "ZQdJM",
        "maxWidth",
        "dispatchEvent",
        "hideButton",
        "closeOtherSubMenu",
        "animateColors",
        "Recent",
        "HeECE",
        "AlbumInLine",
        "bottom-0",
        "childList",
        "!mr-0",
        "lfPeW",
        "lyricWithTranslation",
        "min-h-[calc(100vh-1px)]",
        "head",
        "icon",
        "nZkwq",
        "opacity-50 will-change-transform transition-transform duration-250 mt-2.5 mb-0",
        "meta_arrowup",
        "k4Wv",
        "ContextMenuGroup",
        "handleSubmit",
        "mt-0",
        "progressRef",
        "activeColorsPosDiff",
        "张碧晨",
        "FcQdC",
        "NdrqG",
        "srszlqlvcqfocihoejaahrppxminkwxzkdtdwnjbevuybgguymft",
        "blob",
        "李荣浩",
        "王贰浪",
        "abs",
        "/api/artist",
        "clientWidth",
        "data-v-02d9272f",
        "animation",
        "download.cover",
        "N2wl",
        "LbJhl",
        "h-70px w-70px mr-4 rounded-lg",
        "AvatarCard",
        "luminosity",
        "other-state",
        "Content-Type",
        "flex w-full items-center font-harmony",
        "GKxXC",
        ".css",
        "/api/miauth/paopao?t=",
        "resume",
        "mx-context-menu-item-sperator mx-context-no-clickable",
        "blur",
        "NcIYY",
        "tlyric",
        "mx-context-menu-updown mx-context-no-clickable up",
        "text-btn !text-[initial] !px-3 backdrop-filter backdrop-blur-lg",
        "setSizeAttributesNameSpace",
        "zq34",
        "REPEAT_LIST",
        "removeBodyEvents",
        "2xl",
        "lanzou",
        "scrollTop",
        "no-referrer",
        "GvKKk",
        "rMeLi",
        "power2.out",
        "郁可唯",
        "flex flex-col border-r",
        "新密码，至少为6个字符",
        "/api/playlist/cover/update",
        "half-divider",
        "fnZNP",
        "seekforward",
        "b0c88be8cbfaa2f650620d9eac3dbefb",
        "getElement",
        "SQTMS",
        "clearRect",
        "setSrc",
        "previousTimeStamp",
        "onGradientChange",
        "写入失败",
        "flex-y-center text-base",
        "globalCompositeOperation",
        "is-history",
        "alert",
        "normal",
        "touches",
        "Dev Test",
        "KoGEg",
        "setNextPlayerMode",
        "tooltip",
        "remove",
        "https://p1.music.126.net/XX8qcU-G2EFe4tbanLjIIw==/109951167087325545.jpg?param={size}y{size}",
        "yaSYK",
        "captchaRes",
        "onBodyClick",
        "detail",
        "subtitle",
        "mr-0.1 !text-$text text-16px font-bold superellipse",
        "因為版權方要求，不再提供歌單服務。",
        "flex flex-1 p-1 rounded-full bg-$color-secondary space-x-1",
        "VkYTm",
        "firstScrollInit",
        "JgRnz",
        "granim:gradientChange",
        "slGDi",
        "prefix",
        "breakpoints",
        "pl-4 min-w-0",
        "CLAhw",
        "transitionend",
        "sfHdn",
        "auth.email",
        "确认密码",
        "divided",
        "origin",
        "rBwBA",
        "onEnd",
        "removeItem",
        "map",
        "playlistUpdate",
        "https://p1.music.126.net/lPRzEgNQe2BR-7-nIP_Stw==/109951165691937280.jpg?param={size}y{size}",
        "player.previous",
        "https://i.biliimg.com/bfs/im/908f0f0e388a7c6a3846a20359e4a1ce242118ac.png@{size}w_{size}h_1c.webp",
        "block !important",
        "flex flex-wrap",
        "data-v-e7cd654a",
        "customDirection",
        "rgb",
        "Vinida (万妮达)",
        "$el",
        "h-full overflow-y-auto w-full",
        "!bg-transparent h-15 leading-15 w-full border-none pl-1",
        "$patch",
        "changeDirection",
        "data-v-05801ce8",
        "kK0D",
        "tkWZC",
        "flex-center flex-col mt-8",
        "bg-$color-fill-3 pointer-events-none",
        "detailFirst",
        "https://p1.music.126.net/87vq44o-RhgpUSu0QbeRow==/1419469526616922.jpg?param={size}y{size}",
        " :(",
        "Buffered",
        "disabled",
        "class",
        "https://p1.music.126.net/SKvkD2uPkcdUPwok9dZ6Yw==/109951167693663659.jpg?param={size}y{size}",
        "callback",
        "MobileModal",
        "request.error",
        "SKIP_WAITING",
        "d12499721",
        "https://p1.music.126.net/HTXB834S72ulGPL1oM-RCg==/109951167728753946.jpg?param={size}y{size}",
        "targetTouches",
        "/api/playlist/create",
        "4334FBaWyx",
        "engine",
        "beforeEach",
        "KKECHO",
        "newpassword",
        "Playlist",
        "activeState",
        "player.singlePlay",
        "Unable to preload CSS for ",
        "itemLabelRender",
        "InfiniteLoad",
        "boolean",
        "mNZBd",
        "REPEAT_SONG",
        "include",
        "seekbackward",
        "logout",
        "[name] - [artist]",
        "DarkMuted",
        "wowpm",
        "currentColorsPos",
        "192",
        "https://i.biliimg.com/bfs/im/6ee826e626883b170735e0b02e9d5bd45f7fc554.webp@{size}w_{size}h_1c.webp",
        "order-2 will-change-transform w-full",
        "IvdeM",
        "283160LYGnzr",
        "https://p1.music.126.net/Wj6YO6c3JIRVTm7Qmc7Iyg==/1383185640161007.jpg?param={size}y{size}",
        "searchHistory",
        "setPlayerList",
        "absolute inset-0 w-full h-full object-cover",
        "height",
        "/album/:id",
        "clearPlaylist",
        "delSong",
        "popup-container",
        "order-5",
        "formatTooltip",
        "cancelToken",
        "encode",
        "data-v-49ee5011",
        "globalProperties",
        "歌单描述最多200个汉字",
        "playNext",
        "XlanO",
        "mSbJJ",
        "2000",
        "mb-4 text-$color-neutral-6",
        "「Fuck You」",
        "-my-3",
        "contextmenu.collection",
        "lyricDelay",
        "PlayQueue",
        "exports",
        "beta",
        "mt-15vh",
        "px-2",
        "duration-400 ease-in",
        "font-medium select-text !mb-2 !text-3xl !<sm:text-lg",
        "validate",
        "flex justify-between items-center space-x-2 mt-2 px-2",
        "HtwOi",
        "ZGIJj",
        "https://p1.music.126.net/TQEik9NnhIQ75dZ11TnfYA==/109951165137141788.jpg?param={size}y{size}",
        "华晨宇",
        "MRNsd",
        "call",
        "lleGt",
        "Jony J",
        "RchFE",
        "pcFMZ",
        "KEQdE",
        "Sfkgw",
        "my-0",
        "kMHku",
        "settings.playlist",
        "title",
        "closeWhenScroll",
        "icon-mute",
        "KuAOW",
        "function",
        "empty",
        "!mx-2",
        "ca-pub-8773997952639831",
        "download.unable",
        "items",
        "LightMuted",
        "mx-menu-host",
        "truncate w-full",
        "uuDXj",
        "漠河舞厅·2022.mp3",
        "inline-flex items-center justify-between w-full",
        "d29588305",
        "token",
        "ltQoq",
        "overflow-hidden ml-2",
        "muted",
        "Ubnln",
        "沙一汀EL",
        "CxqRD",
        "arco-locale",
        "dwtkk",
        "d12570417",
        "calc(",
        "download.coverText",
        "/api/search/album",
        "参数id必须为数字！",
        "text-btn !text-$color-text-2",
        "LyricControlbutton",
        "min",
        "xFrTB",
        "XDCVL",
        "light",
        "query",
        "arco-notification pwa-toast",
        "content",
        "w-32px h-32px",
        "imgOriginalWidth",
        "lrc",
        "$emit",
        "refreshColorsAndPos",
        "歌单介绍",
        "username",
        "extra",
        "write",
        "setItem",
        "TopSong:",
        "showIcon",
        "data-v-3e4ab373",
        "change",
        "href",
        "table.duration",
        "data-v-b80771b5",
        "RBWq",
        "disable",
        "BegXQ",
        "https://p1.music.126.net/ArbpVuafLfcdRAPDi4JTDA==/109951167896179360.jpg?param={size}y{size}",
        "img",
        "Settings",
        "time",
        "every",
        "https://p1.music.126.net/T-HudMiTDp3iSgSfkkhqmQ==/109951165134947137.jpg?param={size}y{size}",
        "TNyXG",
        "pid",
        "nextSongs",
        "addState",
        "English",
        "d12788674",
        "onClick",
        "VSbki",
        "itemlist",
        "forward",
        "off",
        "!w-10",
        "https://p1.music.126.net/2TV_J8tFtFYEcnAFRjGr5w==/109951165476544036.jpg?param={size}y{size}",
        "Layout",
        "some",
        "PcRZR",
        "BNtWE",
        "yFXbU",
        "delsub",
        "fixed inset-0 w-full h-full -z-1",
        "焦迈奇",
        "message",
        " | MyFreeMP3",
        "PpacT",
        "absolute flex-center inset-0 bg-$color-neutral-1 text-$color-neutral-4",
        "CoverRow",
        "mt-0.5 cursor-pointer truncate opacity-50",
        "ykADd",
        "XkcWH",
        "MgNYC",
        "toggleMute",
        "Wxjy",
        "ogBUi",
        "player.singleLoop",
        "updateSeek",
        "PzCNC",
        "find",
        "#splash",
        "xOffset",
        "fuUNe",
        "https://p1.music.126.net/UHE1Yoj23HcNvxMjKaq8TA==/109951167431118886.jpg?param={size}y{size}",
        "zIndex",
        "contextmenu.nextPlay",
        "旧密码",
        "items-center",
        "WOzPp",
        "取消收藏成功",
        "TGDgV",
        "isHistory",
        "settings.playStrategy1",
        "https://p1.music.126.net/SZci-Drl-nWi-wpoytvEsQ==/109951165663277602.jpg?param={size}y{size}",
        "/api/auth/sign",
        "END",
        "mt-1",
        "Album",
        "https://p1.music.126.net/vQR_RyWqA459KtXsFk4zig==/109951166564724055.jpg?param={size}y{size}",
        "w-50 h-50 <sm:w-35 <sm:h-35",
        "mt-2",
        "text-$color-text-2",
        "itemType",
        "itemRightArrowRender",
        "编辑歌单信息成功！",
        "msg",
        "opacity-58",
        "prepareImage",
        "https://p1.music.126.net/3WhzK6ozFXUsNutDU566ZA==/6641050233030995.jpg?param={size}y{size}",
        "ContextMenuSperator",
        "ocTnF",
        "text-$color-text-2 ml-2",
        "ZETYn",
        "pl-2",
        "visible",
        "open",
        "LDOZv",
        "change:input",
        "lbQdg",
        "陈壹千",
        "createWritable",
        "mr-2 relative",
        "qcJSS",
        "PnIpw",
        " 2022年3月26日 已关闭新用户注册 ",
        "status",
        "ADKIy",
        "event",
        "SDEhu",
        "mt-3",
        "adjustSubMenuPosition",
        "clientX",
        "lxUzN",
        "DFvuB",
        "mHmkG",
        "replace",
        "flex justify-end playQueueButton",
        "left",
        "itemIconRender",
        "data-v-b80f89ee",
        "ratechange",
        "kZon",
        "config",
        "https://p1.music.126.net/Kqx0dEl5scrp07q_V_CntQ==/109951164312904511.jpg?param={size}y{size}",
        "menu.createdPlaylist",
        "fillRect",
        "reduce",
        "0px",
        "` could not be found in the DOM",
        "!text-$text !bg-$color-secondary-hover !cursor-default",
        "https://p1.music.126.net/Bi3k69dJxvrx-JGojRs7Lw==/109951164897967016.jpg?param={size}y{size}",
        "vertical",
        "setCurrentSong",
        "rgba",
        "overflow-hidden mt-1 px-2 h-full",
        "Ngna",
        "onPlay",
        "arco-theme",
        "N2Wo",
        "addOpenedSubMenu",
        "⌘ K",
        "recommendSong",
        "ended",
        "TJMvU",
        "KdwvU",
        "RIDMD",
        "Higher Brothers",
        "meta_arrowleft",
        "maxTouchPoints",
        "onOpen",
        "ESC",
        "getColor",
        "zen5",
        "truncate",
        "interceptors",
        "item relative rounded-md transition-colors",
        "register",
        "zh-TW",
        "InfoCard",
        "1|6|2|5|0|4|7|3|8",
        "w-35 mx-auto",
        "code",
        "touchAction",
        "-light",
        "关于ios后台播放",
        "toggleShowLyric",
        "徐秉龙",
        "absolute top-[50%] -mt-20px right-0 h-40px z-9",
        "MTfBr",
        "findIndex",
        "密保问题",
        "LINK",
        "formRef",
        "px)",
        "dVBtg",
        "3223584SYAnUP",
        "security",
        "BwQpn",
        "flex overflow-hidden",
        "stretchMode",
        "fFnbE",
        "GCxJN",
        "getUri",
        "toggleShowPlayQueue",
        "徐佳莹",
        "ExploreArtist",
        "XWinp",
        "isMyPlaylist",
        "著作権者が要求しているため、歌単サービスは提供されていない。",
        "menu.subscribedPlaylist",
        "rduQG",
        "color:red;font-size:2em;font-weight:bold",
        "Search",
        "getPropertyValue",
        "querySelector",
        "新建歌单",
        "transformOrigin",
        "LyricRightQueue",
        "jsonpCallback",
        "!w-full !h-full pt-[100%]",
        "btn",
        "stop",
        "recent",
        "metadata",
        "createEvent",
        "UJEbj",
        "w-12",
        "flex-center flex-col",
        "calc(var(--vh, 1vh)*100 - ",
        "rgba(173, 180, 189, 0.6)",
        "removeChild",
        "postMessage",
        "mediaSession",
        "8W2a",
        "showUp",
        "stopPropagation",
        "https://p1.music.126.net/htZBUaMOnJqHLKsUL5Mkrw==/109951167140367485.jpg?param={size}y{size}",
        "./lang/zh-CN.d36740e3.js",
        "VSRqK",
        "4336550278",
        "colorsPosDiff",
        "hover:bg-$color-fill-3",
        "playPrevious",
        "stylesheet",
        "playbackRate",
        "pauseWhenNotInView",
        "JQmmu",
        "arrow w-full left-0 right-0 h-2",
        "https://p1.music.126.net/akdwts0ajGDRQaKZWg34uA==/109951167519169817.jpg?param={size}y{size}",
        "playerState",
        " 应用设置 ",
        " TOP 50",
        "div",
        "data-v-9ed4f065",
        "GpDNK",
        "1600px",
        "matched",
        "Controlbutton",
        "channelsIndex",
        "Hhrgd",
        "no-scrollbar flex overflow-x-auto space-x-4",
        "/api/playlist/info",
        "overlay-MobileModal",
        "flex px-6 space-x-2",
        "getPalette",
        "windows",
        "Kirsty刘瑾睿",
        "select-text",
        "UlXtE",
        "darken",
        "refresh",
        "color",
        "request.unkown",
        "catRef",
        "async",
        "currentColors",
        "table.up",
        "winding",
        "tip",
        "getCurrentColorsPos",
        "xjbeN",
        "update:playlist",
        "d1143033",
        "44px",
        "supports",
        "TcOqW",
        "verify_code",
        "ctrl_arrowright",
        "https://p1.music.126.net/iDyW-cvqOLkuQbuz0smYYQ==/109951164764858797.jpg?param={size}y{size}",
        "body",
        "写入失败: ",
        "d31561897",
        "CNwAO",
        "xBcBW",
        "settings.incVolume",
        "onScroll",
        "transitionSpeed",
        "updateRate",
        "告五人",
        "MyFreeMP3：1.5.65",
        "queueListRef",
        "player.randomPlay",
        "onBodyWhell",
        "is-edit",
        "data-v-00a66cdf",
        "storage",
        "appendChild",
        "progress",
        "onload",
        "h-full",
        "getItemDataForChildren",
        "kpja",
        "join",
        "max-w-[calc(100vh-238px)] mb-6 mx-auto",
        "getItem",
        "activeColorsPos",
        "rel",
        "https://p1.music.126.net/hcwPSdlU235A9VENxlOl2g==/109951167507013622.jpg?param={size}y{size}",
        "init",
        "button",
        "togglePlay",
        "song",
        "OwNYH",
        "by ",
        "OQWfc",
        "用户名",
        "!w-40px !h-40px",
        "INPUT",
        "desc",
        "del",
        "LkAim",
        "ENAVs",
        "getDimensions",
        "length",
        "LOADING",
        "LightVibrant",
        "pauseWhenNotInViewNameSpace",
        "host",
        "d12236125",
        "relList",
        "embed",
        "modelValue",
        "setLocaleMessage",
        "vec_hotkey",
        "__VUE__",
        "你还没有创建歌单",
        "touchend",
        "autofocus",
        "menu.my",
        "coordsStart: ",
        "QdiWl",
        "ERkJe",
        "XPRNQ",
        "+0.5s",
        "source",
        "settings",
        "stretch-if-bigger",
        "image.stretchMode",
        "screen",
        "#17171a",
        "charAt",
        "isPaused",
        "toString",
        "oldpassword",
        "method",
        "发生未知错误",
        "-hh-7+2h-1m-4u",
        "RecommendSong:",
        "center",
        ".ts",
        "1.5x",
        "热门搜索",
        "isMuted",
        "_blank",
        "NCQln",
        "播放模式",
        "editable",
        "wWizR",
        "R49q",
        "imgOriginalHeight",
        "animating",
        "getLightness",
        "PIdjg",
        "size",
        ".arco-scrollbar-container",
        "https://p1.music.126.net/SC4xC0MMlPC4nViAO0768g==/109951163676566884.jpg?param={size}y{size}",
        "sIDAg",
        "更新成功",
        "match",
        "my-2",
        "kiATF",
        "flex-y-center font-medium text-2xl mb-2 mt-4 font-smiley",
        "top: ",
        "installBodyEvents",
        "/user",
        "/explore",
        "myfreemp3",
        "SearchModalContent",
        "!rounded-xl transform",
        "children",
        "flex-center w-32px h-48px",
        "tab",
        "陈奕迅",
        "number",
        "mask absolute inset-0 flex-center bg-[#3c3c3c70] text-white duration-500 transition",
        "shuffledList",
        "line line-2",
        "firstElementChild",
        "薛之谦",
        "mt-4px text-12px truncate",
        "iconfont",
        "download.song",
        "adsbygoogle",
        "yGlcv",
        "OJbaS",
        "大一点",
        "h-15",
        " 修改密码 ",
        "杨宗纬",
        "isArray",
        "bg-$bg",
        "CallBack",
        "mx-menu-ghost-host",
        "nrmWd",
        "unshift",
        "rules",
        "UserInfo",
        "https://p1.music.126.net/VGnB9gbxE1xHs6nsxNMh9A==/109951164639836060.jpg?param={size}y{size}",
        "p-1.5 m-2px rounded-md cursor-pointer",
        "session",
        "tabs",
        "0.5x",
        "ELEMENT_NODE",
        "/api/playlist/privacy",
        "PAUSE",
        "zQtBD",
        "image.position",
        "highlight",
        "left-right",
        "#content",
        "请输入新歌单标题",
        "flex-col truncate",
        "/name/",
        "-icon-",
        "absolute",
        "uOQDU",
        "Lyric",
        "GwyLx",
        "KSvEP",
        "home.artist",
        "CgpvY",
        "eIPcG",
        "order-1",
        "userAgent",
        "success",
        "var(--color-fill-3)",
        "headers",
        "bhugT",
        " 由于ios限制无法在后台切换歌曲，可以添加到主屏幕、升级到ios16.1.1",
        "lOIzU",
        "新密码",
        "https://p1.music.126.net/UCAHaG-61YTw36aKlVJrmw==/109951165851372781.jpg?param={size}y{size}",
        "暂无歌词",
        "HGZmP",
        "UUlha",
        "./lang/en-US.3c1578e5.js",
        "TlArB",
        "utKcL",
        "scrollList",
        "isCurrentColorsSet",
        "棱镜乐队",
        "128",
        "播放设置",
        "settings.disableAnimation",
        "max-w-85 w-full m-auto pt-[5vmin]",
        "play",
        " MyFreeMP3 ",
        "mb-2 min-h-120px",
        "https://p1.music.126.net/nDHmzzJFCPnqbdFEkZh9eA==/109951163534426092.jpg?param={size}y{size}",
        "platform",
        "fetchStreamingAction",
        "header",
        "contextmenu.viewArtist",
        "自建歌单",
        "globalHasSlot",
        "onChange",
        "timer",
        "iQBcB",
        "https://p1.music.126.net/EawqbkXCxGmxZ6nnqTKxKw==/109951165566992331.jpg?param={size}y{size}",
        "rGfJJ",
        "Player",
        "bLyAH",
        "yOffset",
        "triggerError",
        "XMASwu(吴骜)",
        "DndProvider",
        "20241016.",
        "scrollWidth",
        "text-xl font-semibold",
        "wheel",
        "bc-none",
        "no-underline cursor-pointer",
        "aside",
        " - ",
        "kill",
        "ContextMenuItem",
        "load",
        "KnowKnow",
        "2055664GkbBWt",
        "data-v-efd859b4",
        "设置为隐私歌单",
        "submit",
        "trackColor",
        "expireTime",
        "YoHuT",
        "szkuA",
        "noMore",
        "HpUno",
        "resetFields",
        "superellipse",
        "data-v-1908228c",
        "playing",
        "hotSongs",
        "256",
        "Event",
        "oOKWD",
        "direction",
        "MYfqI",
        "settings.action.locale",
        "model-value",
        "mxZaI",
        "drag_window",
        "cacheKey",
        "fdwEe",
        "密码至少为6个字符",
        "data-v-52ea3f6d",
        "destroy",
        "coordsEnd: ",
        "写入成功: ",
        "getAttribute",
        "moveList",
        "修改成功",
        "callbacks",
        "nAAlF",
        "space-x-1",
        "history",
        "subscribe",
        "danquxunhuan1",
        "events",
        "stateTransitionSpeed",
        "/api/search",
        "push",
        "login",
        "ReloadPrompt",
        "<md:text-center text-lg",
        "getItemType",
        "target",
        "https://p1.music.126.net/zHOzt1gGsUmNMMA6g8FQ5w==/109951165824760904.jpg?param={size}y{size}",
        "opacity",
        "mr-2 flex-shrink-0",
        "https://p1.music.126.net/Kwr9wbqqncajark2P3bCGg==/109951167626611050.jpg?param={size}y{size}",
        "data-v-ce358e8f",
        "VJDAI",
        "d7424",
        "router-link",
        "line whitespace-pre-wrap leading-16 md:p-5 px-0 py-4",
        "baidupan",
        "meta",
        "highlightIndex",
        "App",
        "max",
        "showAlbum",
        "d12121264",
        "isPausedBecauseNotInView",
        "iLYlj",
        "UOlIH",
        "avatar.login",
        "滑动抽屉组件测试",
        "wNQHy",
        "refScrollbar",
        "flex-y-center <md:flex-col",
        "qVUYO",
        "elastic.out(1,0.5)",
        "relative min-h-0 md:ml-8 md:max-w-50vw md:w-50vw lg:max-w-40vw lg:w-40vw",
        "active",
        "html5",
        "kV02",
        "MediaMetadata",
        " icon ",
        "album",
        "https://p1.music.126.net/VJLUv2HtobEqsfvE4H8xNg==/109951163464459383.jpg?param={size}y{size}",
        "showSubMenu",
        "Aioz",
        "[name]",
        "data-v-d4881c24",
        "auth.btn.login",
        "flex-1 text-right",
        "change:loading",
        "vue：",
        "innerHeight",
        "text-btn w-16 h-16 <md:w-13 <md:h-13 superellipse opacity-50 hover:opacity-100",
        "createElement",
        "get",
        "home.song",
        "now",
        "mb-3",
        "subtitle text-xs truncate opacity-88",
        "SearchModalInput",
        "JJjeq",
        "h-70px !text-$color-text-2 text-xs flex flex-col",
        "download.copyTip",
        "md:p-5 px-0 py-4 rounded-xl opacity-50",
        "yAlSh",
        "mahyG",
        "creator",
        "picRef",
        "colorType",
        "text-btn !text-$color-text-2 !px-2",
        "QYvlY",
        "https://p1.music.126.net/n3xTPeo2r-H_nSz6_4hEUA==/109951167342725530.jpg?param={size}y{size}",
        "getBoundingClientRect",
        "https://p1.music.126.net/9AxOvJQqBkMY0pHC9VbPCw==/109951162809089968.jpg?param={size}y{size}",
        "end",
        "page",
        "JXtDP",
        "setSizeAttributes",
        "Album:",
        "ISshW",
        "取回密码失败",
        "finally",
        "cover-row relative overflow-hidden cursor-pointer pt-[100%]",
        "rows",
        "nIiUQ",
        "-mb-24px border-b w-full px-4 flex items-center",
        "dOYUw",
        "PlayerMode",
        "因为版权方要求，不再提供歌单服务。",
        "states",
        "reset",
        "leading-[1.1] max-w-100/130",
        " 本站本身不储存任何资源文件，资源来自互联网，仅供学习交流试听，请于下载后24小时内删除，支持购买正版专辑！ ",
        "IKBAf",
        "flex",
        "gBnZE",
        "HPbIO",
        "IDLE",
        "Recommend",
        "scRPP",
        "px + var(--vueuse-safe-area-bottom))",
        "checkLoading",
        "https://p1.music.126.net/OZh9Xp2iiyu93HOCXtxwqA==/5927467185648928.jpg?param={size}y{size}",
        "d12395355",
        "random",
        "79580vfRgvP",
        "meta_arrowdown",
        "ctrl_k",
        "confirm",
        "iNEkj",
        "input:focus,textarea:focus",
        "tags",
        "openMenu",
        "queueHeaderRef",
        "zQ49",
        "已设置。密码至少6位字符，支持数字、字母和除空格外的特殊字符，且必须同时包含数字和大小写字母。",
        "container",
        "log",
        "maskRef",
        "Home",
        "list",
        "data-v-27d6b3c4",
        "text-3xl <md:text-lg <sm:text-base transition min-h-full",
        "test",
        "k7jl",
        "jyXLQ",
        "/api/lyric",
        "https://p1.music.126.net/daqU7RiA2mfTneyWQn2ZOg==/109951163582530189.jpg?param={size}y{size}",
        "pb-2",
        "bg_wrapper absolute overflow-hidden -z-1 -top-10vh left-0 right-0 h-470px",
        "无标题",
        "QueueHeader",
        "data-v-ee792174",
        "data-v-26c536be",
        "isImgLoaded",
        "z8J2",
        "trueMode",
        "ko-KR",
        "cursor-pointer hover:bg-$item-hover transition",
        "bCydL",
        "PHyzD",
        "dark",
        "DEifi",
        "获取数据: ",
        "blendingMode",
        "Neo5",
        "200px",
        "ZAMRz",
        "reloadPrompt.update",
        "NVJvO",
        "#fff",
        "top-btn",
        "response",
        "-0.5s",
        "NPl7",
        "ioxJd",
        "keywords",
        "hash",
        "textarea",
        "1200px",
        "!h-10",
        "showCover",
        "data-v-211b59cd",
        "startY: ",
        "https://p1.music.126.net/5Lr8ZVI-qvcQDaw55Cx-Zg==/109951165177845814.jpg?param={size}y{size}",
        "auth.forgot",
        "navigator",
        "NP51",
        "testPassive",
        "create",
        "currentTime",
        "搜索结果",
        "contextmenu.lyricSize",
        "global",
        "space-x-4",
        "isShuffled",
        "ExplorePlaylist",
        "CustomEvent",
        "ahblN",
        "QQTLx",
        "mousemove",
        "label",
        "===",
        "xffvrhtlezcvmasnsdkjuqbkcgxizyormeatwdujhpglpwyboniq",
        "BTdbe",
        "thumb",
        "offsetHeight",
        "auth.user",
        "download.320",
        "vnode",
        "router-view",
        "update:isHistory",
        "48px",
        "onRefresh",
        "artist",
        "bg-white text-[#222]",
        "UserAvatar",
        "dSEag",
        "initCustomEvent",
        "absolute z-1 right-3 top-3 sm:right-8 sm:top-8 flex flex-col gap-2",
        "arg",
        "SWyHG",
        "cdclk",
        "FzSkN",
        "max-w-100",
        "isOver",
        "Unknown variable dynamic import: ",
        "5px",
        "AKoHS",
        "https://p1.music.126.net/Ypy6DuNsM9dUDAi-daXjmg==/2540971374930594.jpg?param={size}y{size}",
        "defaultZindex",
        "https://",
        "capiN",
        "contextmenu.lyricOffset",
        "addSongs",
        "3rem",
        "opXDZ",
        "gradientChange",
        "10nzFCoB",
        "14qZrUPJ",
        "倍速播放 (",
        "lxGrG",
        "MobileModal test",
        "--vh",
        "693300wMHiJz",
        "GET",
        "ePeNE",
        "positioning",
        "UgYin",
        "h-10 flex-y-center justify-between",
        "d31309410",
        "hTGeF",
        "text-16px leading-6 space-y-3",
        "responseURL",
        "mb-6",
        "update:isEdit",
        "pause",
        "yVrTO",
        "https://p1.music.126.net/qmR3rXVA5TarwtumEjVgEw==/109951165702046669.jpg?param={size}y{size}",
        "documentElement",
        "context",
        "/api/lyric/id/",
        "flex flex-col bg-$color-fill-1 p-2 mb-4",
        "DEFAULT",
        "isSwiping: ",
        "XqJod",
        "/explore/artist",
        "/api/artist/list",
        "cors",
        "download.2000",
        "张国荣",
        "pass",
        "https://p1.music.126.net/q-I4cF6k7MJ5K_fRxEvozg==/109951163511967669.jpg?param={size}y{size}",
        "-subtitle",
        "zj2B",
        "innerWidth",
        "data-v-4fd854ff",
        "https://p1.music.126.net/iHVX4p12jdQsyEosLhDGQg==/109951165830678577.jpg?param={size}y{size}",
        "Result",
        "text-center",
        "click",
        "参数错误，编辑歌单信息失败！",
        "mb-8",
        "ygPMj",
        "font-bold text-18px leading-tight",
        "您暂未设置密保问题，密保问题可以有效的保护账号的安全。",
        "mx-right-arrow",
        "drawImage",
        "PLAYING",
        "IpfEO",
        "object",
        "isDragging",
        "toggleShuffleSongList",
        "topMenu.recommend",
        "urWPx",
        "$persistedState",
        "$props",
        "toLowerCase",
        "mb-2 text-3xl font-bold",
        "VUuAI",
        "lyric",
        "getSourceClientOffset",
        "SearchSong",
        "getColorPosDiff",
        "object-cover",
        "https://p1.music.126.net/1KQVD6XWbs5IAV0xOj1ZIA==/18764265441342019.jpg?param={size}y{size}",
        "SVYku",
        "mx-context-menu-item-wrapper",
        "isChangingState",
        "/api/user/detail",
        "settings.shortcuts",
        "groups",
        "Playlist:",
        "referrerpolicy",
        "auth.userAndEmail",
        "text-btn max-w-full truncate !block !px-2",
        "playQueue.clearListTitle",
        "leading-6",
        "color-burn",
        "mx-auto",
        "topSong",
        "startTime",
        "captchaObj",
        "paddingRight",
        "AXRej",
        "basis-1/4",
        "color-dodge",
        "lpgAx",
        "ContextSubMenu",
        "Rrp0",
        "邮箱格式错误",
        "ListItem",
        "h-10",
        "[data-postimg=\"",
        "jZAbq",
        "hsl",
        "刘思鉴",
        "保存成功: ",
        "onResize",
        "cancelable",
        " · ",
        "ElfSo",
        "vbPof",
        "data-v-1b322d90",
        "-icon-tip",
        "yUriV",
        "space",
        "密码不能为空",
        "appContext",
        "xGBZW",
        "$route",
        "cacheEmptyValue",
        "https://i.biliimg.com/bfs/im/28992b83a58081a50f36f0c36db49c7d1c2afd2f.jpg@{size}w_{size}h_1c.webp",
        "https://p1.music.126.net/31QAzJPNmYzZIpx-iAcy0g==/109951165432652392.jpg?param={size}y{size}",
        "15vh",
        "/settings",
        "Esc",
        "5398155jzbXHn",
        "h-120px text-red-800",
        "start",
        "text-right",
        "settings.decVolume",
        "setLyricDelay",
        "音阙诗听",
        "XqAHK",
        "#555",
        "getColorDiff",
        "songList",
        "Menu",
        "image/jpg",
        "onMouseEnter",
        "NoQy",
        "line line-1",
        "/artist/:id",
        "setProgress",
        "modal-mask absolute inset-0 bg-$color-mask-bg",
        "bcjgr",
        "placeholder",
        "opt",
        "className",
        "toFixed",
        "KXkOx",
        "/api/link",
        "text-",
        "data-v-f395848d",
        "oegdcjlhzkwifilqmmntawrpcjgoevstuuvhnxzdyxqrykpbfabs",
        "不是花火呀",
        "initialData",
        "hexa",
        "forEach",
        "setColors",
        "mittInstance",
        "kyxK",
        "bottom",
        "nickname",
        "value",
        "YNjKV",
        "colors",
        "key",
        "onDblclick",
        "张学友",
        "var(--color-bg-1)",
        "请先登录！",
        "isMySubscribe",
        "settings.namedRules",
        "clear",
        "/:pathMatch(.*)*",
        "已添加到播放列表",
        "same-origin",
        "nodeType",
        "$reset",
        "/api/user/password/update",
        "./lang/ko-KR.0a309272.js",
        "playQueueButton",
        "settings.preset",
        "PasswordFind",
        "ins",
        "250px",
        "showCaptcha",
        "flex-grow <lg:hidden",
        "offsetWidth",
        "nodeName",
        "aCdRd",
        "$router",
        "makeGradient",
        "IjvEL",
        "scrollRef",
        "splice",
        "pic",
        "NZnN",
        "mousedown",
        "description",
        "easeOut"
    ]
}
r=function Co(e, t) {
    const n = qo();
    return (Co = function(e, t) {
        return n[e -= 237]
    }
    )(e, t)
}
my_encode=function(e, t) {
    const n = r
      , s = {
        ZbMoW: function(e) {
            return e()
        },
        CxqRD: function(e, t) {
            return e(t)
        },
        qVUYO: function(e, t, n) {
            return e(t, n)
        }
    };
    if (void 0 === t && (t = s[n(1065)](Ds)),
    s[n(1388)](As, window) === n(832)) {
        function u(data){
            return CryptoJS.MD5(data).toString()
        }
        var o = s[n(1969)](Os, t[n(1750)](), e[n(1750)]());
        return n(1884) + s[n(1388)](u, function(e) {
            const t = r
              , n = {
                UMPFo: function(e, t) {
                    return e | t
                }
            }
              , s = t(527)[t(679)]("|");
            let o = 0;
            for (; ; ) {
                switch (s[o++]) {
                case "0":
                    var i, a, l, c, u, d, p, m, h = 0, f = "";
                    continue;
                case "1":
                    return (y ? f[t(957)](0, y - 3) : f) + t(2118)[t(957)](y || 3);
                case "2":
                    if (!e)
                        return e;
                    continue;
                case "3":
                    do {
                        i = e[h++],
                        a = e[h++],
                        l = e[h++],
                        c = (m = n[t(692)](i << 16, a << 8) | l) >> 18 & 63,
                        u = m >> 12 & 63,
                        d = m >> 6 & 63,
                        p = 63 & m,
                        f += Is[t(1748)](c) + Is[t(1748)](u) + Is[t(1748)](d) + Is[t(1748)](p)
                    } while (h < e[t(1721)]);
                    continue;
                case "4":
                    var y = e[t(1721)] % 3;
                    continue
                }
                break
            }
        }(o))
    }
    String[n(1076)][n(1750)] = function() {}
}
// data='{"type":"YQM","text":"some","page":1,"v":"beta","_t":1738933832764}'
// console.log(encodeURIComponent(data))
function token(data){
    let new_data = encodeURIComponent(data)
    return my_encode(new_data)
}

console.log(token('{"type":"YQM","text":"some","page":1,"v":"beta","_t":1738938183794}'))